### ISSUE TITLE
 Delete should not show up or should be disabled for triggers

### ISSUE THREAD

**Issue by hartra344** [Azure/LogicAppsUX#1113]
AB#15929300

AB#16140942

**Comment by pixelmimic** [comment]
What was the reason for this? In the original designer, you could do this. 

I'm still relatively new to new to Logic App and so I'm exploring the Triggers. However, now I have to reload the designer rather than remove the trigger and add the correct one. Would it be better to have validation on Save, so that once saved, then it can't be removed?
