### ISSUE TITLE
Drag and Drop is happening from depending branch

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#1613]
### Describe the Bug

Expected: The compose action should not be drag/drop from the dependent for each card.

Actual: Drag and Drop is happening from dependent branch.

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

Drag and drop should move the action properly

### Screenshots or Videos

![Drag Drop](https://user-images.githubusercontent.com/95886809/217109259-2f1d5811-f20b-4b60-9201-63159304980a.JPG)

### Platform And Browser

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

AB#17036984

**Comment by Eric-B-Wu** [comment]
I wasn't able to reproduce this issue, but if no repro can be produced, should verify with vendor team as they saw a discrepancy between ga designer and new designer

**Comment by rllyy97** [comment]
The issue is that in GA we don't allow dragging nodes to positions that make their tokens invalid, like in the screenshot when we move the compose before where the input token is being output.  We either need to just block the move like we do in GA, or remove the invalid tokens after you move.  Just blocking the move without any visible reason as to why might make people confused.
