### ISSUE TITLE
The renderComponentIntoRoot component encountered an error while loading.

### ISSUE THREAD

**Issue by berellax** [Azure/LogicAppsUX#2123]
### Describe the Bug with repro steps

When opening a large Logic App in the Preview Designer, get an error message and the Logic App will not open. The browser console provides a detailed message with fhe following: "Microsoft_Azure_EMA]  6:14:08 AM renderComponentIntoRoot ReactInternalComponentError: {"message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded"}"

### Workflow JSON

```json
Attached
```

### Screenshots or Videos

[Workflow.txt](https://github.com/Azure/LogicAppsUX/files/11321999/Workflow.txt)

### Browser

Chrome

**Comment by ccastrotrejo** [comment]
Hi @berellax, this issue was caused because the function to render the nodes in the workflow is getting recursively calling itself too many times, causing a crash. I looked at your workflow definition at it seems that the `Switch ActionType` node has some errors. Some action nodes inside have the same name as the case, resulting in trying to render itself a lot of time. Specifically, all the else cases of `Create_Lead`, `Update_Contact` and `Update_Lead`. I tried to rename those actions and it seems to work fine.


1. Create_Lead
<img width="1207" alt="Screenshot 2023-04-28 at 3 34 33 PM" src="https://user-images.githubusercontent.com/102700317/235266274-f914216c-9d3c-4e59-9387-701a96a8711c.png">


2. Update_Contact
<img width="1187" alt="Screenshot 2023-04-28 at 3 38 30 PM" src="https://user-images.githubusercontent.com/102700317/235266283-77ea2177-d88c-4d98-b0cc-b9fe5310b8b4.png">

3. Update_Lead
<img width="1400" alt="Screenshot 2023-04-28 at 3 40 21 PM" src="https://user-images.githubusercontent.com/102700317/235266298-a60254fd-443f-4775-a9d7-de80ebeb36f2.png">




After all the changes, this is the final result. You can see that the nodes have different names.
Please, if this is still happening after the changes, feel free to reopen and we can have a deeper dive of why its happening for you
<img width="1117" alt="Screenshot 2023-04-28 at 3 40 57 PM" src="https://user-images.githubusercontent.com/102700317/235265711-11de6b4e-f42a-4ad1-90a0-19f75316d2a9.png">
