### ISSUE TITLE
Prevent metadata from being added on every item change

### ISSUE THREAD

**Issue by Eric-B-Wu** [Azure/LogicAppsUX#2185]
### Describe the Bug with repro steps

1. Choose a File picker editor
2. Choose a file
3. View Code View and see that on serialization we're just appending the item in the metadata objet

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![fix filepicker](https://user-images.githubusercontent.com/95886809/235272573-dd4566a1-24e9-49f0-ba70-09f6bc39fe9d.gif)

### Browser

All

**Comment by hartra344** [comment]
I took a look ata this. From a functionality standpoint I think it might be better to just keep it as is. We don't want to always overwrite metadata and I also don't think it's worth special casing the file picker for this. Since there's no functionality impact and it would take a lot of effort on the customers part of make this something that could come close to a problem, it's likely better to just not be messed with.
