### ISSUE TITLE
Http Webhook_Http webhook option is not present as trigger and action.

### ISSUE THREAD

**Issue by v-prakumar** [Azure/LogicAppsUX#2230]
### Describe the Bug with repro steps

1.Create a lA in standard portal and add http webhook as a trigger and option.

Expected: Http webhook option should be present.

Actual: Http webhook option is not present.
![image](https://user-images.githubusercontent.com/92098490/236166985-257f44ae-adc8-4398-86a2-5696a81eeb4d.png)

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Browser

Edge

### Additional context

**Environment Details:**
**URL:** [https://aka.ms/emastaging](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Femastaging&data=05%7C01%7Cv-prakumar%40microsoft.com%7Cd378f183370b438cc04808db4c71f758%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638187824675810110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KueKs0YevoTJzYNLKQTagBIKHiq4zyNBTfvrrAEieKU%3D&reserved=0) 

**Version:** "2.30501.1.1"

**Comment by ccastrotrejo** [comment]
This issue seems to be working fine now, I couldn't repro. If this issue keeps happening I will open it and take a further look on it.  I tested in different environments

- Standalone app in main branch
<img width="800" alt="Screenshot 2023-05-05 at 1 44 00 PM" src="https://user-images.githubusercontent.com/102700317/236565687-f60f34b9-8d94-4f49-abcc-662d2e2d5bfa.png">

- Standalone app with arm generated token in main branch
<img width="800" alt="Screenshot 2023-05-05 at 1 47 57 PM" src="https://user-images.githubusercontent.com/102700317/236566080-cc3e3a41-fb8f-4474-b725-1acf74fafc3b.png">

- Portal local environment in release/20230501 branch
<img width="800" alt="Screenshot 2023-05-05 at 1 49 58 PM" src="https://user-images.githubusercontent.com/102700317/236566437-579874b5-2f9d-4881-8ec0-4804e165a10f.png">


- In the following url [https://aka.ms/emastaging](https://aka.ms/emastaging)
<img width="800" alt="Screenshot 2023-05-05 at 1 44 38 PM" src="https://user-images.githubusercontent.com/102700317/236565709-e5fde05f-7957-438e-a2a3-590665d7fc27.png">

**Comment by v-prakumar** [comment]
@ccastrotrejo This issue is happening again to me , raising a new item for the same with all the details.
