### ISSUE TITLE
Workflow graph dimensions are reset when passing a modified workflow to the designer

### ISSUE THREAD

**Issue by jaimereyesmx** [Azure/LogicAppsUX#2303]
### Describe the Bug with repro steps 

Right now, when a workflow is present in the designer and a slightly modified workflow gets passed, the designer resets the current workflow graph object and resets the node dimensions. This is a problem for at least two scenarios:

1. The host Saved the workflow in the backend and passes the same workflow to the designer but with additional metadata. 
2. The host has the capability to create new workflows or modify the existing workflow. 

The reason this happens is because the logic to set the graph dimensions is called as part of workflow deserialization, ideally, this logic should be separated so that any calls to deserialization do not reset the dimensions.

For now, a workaround was created by flattening the previous workflow and traversing the new workflow looking for matches in the previous workflow; see [https://github.com/Azure/LogicAppsUX/pull/2239](<https://github.com/Azure/LogicAppsUX/pull/2239>). This solution is not perfect since there might be situations where an action "Send an email" from Outlook connector gets replaced by an action with the same name example "Send an email" from Mail connector.

Here are examples of how the flow layout was messed up before the workaround was implemented:

### Before 

![image](<https://github.com/Azure/LogicAppsUX/assets/12244548/39775992-363c-4d99-9b74-d25d74d00687>)

### After 

![image](<https://github.com/Azure/LogicAppsUX/assets/12244548/ee787161-896d-4d45-a41b-f54b49d424a2>)

### Before 

![image](<https://github.com/Azure/LogicAppsUX/assets/12244548/310d9ff6-11fa-4fe7-8340-8b1971754478>)

### After 

![image](<https://github.com/Azure/LogicAppsUX/assets/12244548/1e495f4a-5ee2-4b46-8d63-dff41c9a5929>)

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using Preview Designer or GA Designer 

Preview

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

All

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@jaimereyesmx - when you call deserialization for a workflow it is supposed to recalculate the entire workflow since new nodes could be added or deleted since you are calling complete deserialization it means something in workflow need to be reloaded.
We should not separate the concept of node deserialization, calculation and populating metadata from here.

If the host has capability of updating metadata in existing nodes, then please have separate methods exposed from the designer which will only update the metadata and does not require repopulation of metadata for all operations like inputs, outputs, settings and so on.

**Comment by jaimereyesmx** [comment]
@preetriti1 node recalculation is not happening when passing a workflow, that is the issue. The deserialization resets the node dimensions to the default state.
