### ISSUE TITLE
Queue trigger condition is simple textbox

### ISSUE THREAD

**Issue by abatishchev** [Azure/LogicAppsUX#2351]
### Describe the Bug with repro steps

1. Create a new workflow
2. Add a new trigger - Azure Queue - On a new message
3. Go to Settings -> General -> Trigger conditions
4. Observe the trigger input is a simple text textbox, doesn't allow inserting Expression or Data from previous steps

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

Trigger conditions:

![image](https://github.com/Azure/LogicAppsUX/assets/351644/dd4943c7-68e6-471e-a23e-b60bcc2c4005)

Other textboxes:

![image](https://github.com/Azure/LogicAppsUX/assets/351644/33ef9d72-3e2c-4575-a8e4-76c47c1bc0b0)

### Browser

Edge version 113.0.1774.35

**Comment by preetriti1** [comment]
@abatishchev - this is not a supported scenario, we do not allow entering expressions in trigger condition since trigger is the entry point of workflow. Also this was not present in our GA designer as well, so closing this as a non bug.
![image](https://github.com/Azure/LogicAppsUX/assets/48265693/6d18b7c6-5340-4467-b8ef-d5e3d608fdf7)

**Comment by abatishchev** [comment]
@preetriti1 can you please explain (or point to the right doc) what should go into the texbox?

Its description says:

> Specify one of more expressions ...

And you're saying:

> we do not allow entering expressions

I'm puzzled by the contradiction. Can you please explain?
