### ISSUE TITLE
VSCode-designer-issue with ForEach and the variable below that

### ISSUE THREAD

**Issue by mhireholi** [Azure/LogicAppsUX#2372]
### Describe the Bug with repro steps

Create foreach and create a variable below that
![foreach-vscode-and-the-variable-issue](https://github.com/Azure/LogicAppsUX/assets/40304643/8165c9ee-9ec8-4a66-a0e8-63e1eece4ad9)

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using Preview Designer or GA Designer

Generally Available

### Screenshots or Videos

![foreach-vscode-and-the-variable-issue](https://github.com/Azure/LogicAppsUX/assets/40304643/d4750b93-d4c8-48cd-875c-5a356a0d3c07)

### Browser

VSCode

**Comment by ccastrotrejo** [comment]
Hi @mhireholi thank you so much for raising this issue. Can you please elaborate a little bit more on what is the issue and what is the expected scenario/look?

**Comment by Eric-B-Wu** [comment]
@ccastrotrejo I'm able to repro this, this happens when there's an uneven parallel branch in a scope card, for example, because the condition node is a lot larger than the normal node, when adding it as a parallel node to a scope node, the scope card becomes off center. 
<img width="727" alt="test" src="https://github.com/Azure/LogicAppsUX/assets/95886809/bfa524ee-c535-419b-bdca-5c0c3235837b">

**Comment by ccastrotrejo** [comment]
Thanks @Eric, I will take a look at that
