### ISSUE TITLE
Unable to save Parameter default values

### ISSUE THREAD

**Issue by hardEight** [Azure/LogicAppsUX#2397]
### Describe the Bug with repro steps

Open Logic App in new designer with multiple Params
Edit String Parameter
Click Save.

Save button is still active, nothing is committed. No change in the Version information. Had to change the Parameter in Code View.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Workflow JSON

```json
Json made the comments to long so I couldn't submit.
```

### Browser

Edge Version 113.0.1774.35 (Official build) (64-bit)

**Comment by hardEight** [comment]
Hi Riley,
The trigger is just an occurrence. (Set times daily). Not sure what you
mean about the managed identity connection, there's a TON of connectors in
this logic app. I'll use GA for now, thanks!!

**Comment by rllyy97** [comment]
> Hi Riley, The trigger is just an occurrence. (Set times daily). Not sure what you mean about the managed identity connection, there's a TON of connectors in this logic app. I'll use GA for now, thanks!!

Managed Identity is just one of the options for connection creation on some of our connectors.
Since I don't think your issue is specific to workflow parameters, and is instead something with our broader saving issues, I'm going to close this issue for now.
If you are still unable to save your workflow parameters by June 2nd, please feel free to reopen this issue and we'll take a closer look!
