### ISSUE TITLE
Dynamic Content not Updated when Action Renamed

### ISSUE THREAD

**Issue by WarrenKinley** [Azure/LogicAppsUX#2405]
### Describe the Bug with repro steps

1. Create a compose shape named "Compose"
2. Add a JavaScriptCode action shape
3. Token pick the "Compose" output, it will insert: workflowContext.actions.Compose.outputs
4. Rename "Compose" shape to something else e.g. "Compose address"
5. Use the token picker again inside the JavaScriptCode action Code box and select the "Compose address" output and it will still insert: workflowContext.actions.Compose.outputs.  It should be inserting: workflowContext.actions.Compose_address.outputs

If you manually rename inside the JavaScriptCode Code it works perfectly.

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/95749950/4038e2e1-7cdd-4c7a-bb94-ea51ceadd8a5)

### Browser

Edge

**Comment by MrRosendahl** [comment]
@preetriti1 this bug shoule be re-opened since this has been re-intruduced in runtime version 1.44.9 in portal... and is really annoying.

Changing an action name or trigger name does not update the cached dynamically content name and the workflow cannot be saved since it will generate an error. The workaround is to change the name with search/replace in code view, not optimal.

![changed_name_is_not_reflected_in_code](https://github.com/Azure/LogicAppsUX/assets/29914665/04c82941-929f-451d-b3db-c859dc33428e)
![Screenshot 2023-11-09 081854](https://github.com/Azure/LogicAppsUX/assets/29914665/7b70f923-1048-47f8-8dcd-ddb3c9a0b3f4)
