### ISSUE TITLE
CORS configuration is not in effect

### ISSUE THREAD

**Issue by hzhunag** [Azure/LogicAppsUX#2705]
### Describe the Bug with repro steps

1.  add https://ms.portal.azure.com to the allowed origins list in the API CORS settings.
2. couldn't see inputs and outputs after wait a few of minutes.
3.  couldn't see inputs and outputs after  restart logic app standard.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

error screenshot
<img width="1336" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/110654212/6e00cbd9-8558-45a7-9331-e38890fe44bc">

console errors
<img width="598" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/110654212/2bcbf030-50b2-4a90-b7d7-5dcaff04facd">

<img width="473" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/110654212/92b91ef0-019d-4588-9769-eed2c5aba268">

### Browser

<img width="558" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/110654212/bd829ce9-dba9-4974-8014-451584a28736">

AB#24216356

**Comment by hartra344** [comment]
@hzhunag do you have any access restrictions on the app? We need CORS added because inputs and outputs data comes from the host itself, not from our API layer. If you have firewall or network access restrictions on the app then that can also cause a failure that looks like a CORS failure to the UI.

If you don't then can you please send me a network trace? travisharris@Microsoft.com
