### ISSUE TITLE
Designer set to readonly should not allow changing connection

### ISSUE THREAD

**Issue by wifun** [Azure/LogicAppsUX#2784]
### Describe the Bug with repro steps

Currently when the designer is set to readonly users can still get to the "Select connection" panel (or if they were already on it) and change the used connection.

We have a specific scenario where we prepare to load a new/updated copy of a workflow, at this time the designer is readonly. If the user changes their connection this change will be ignored (so the UI is misleading).

![image](https://github.com/Azure/LogicAppsUX/assets/55114634/cfe73232-2dd0-4dd0-aaaa-df090568c253)

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using Preview Designer or GA Designer

Preview

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#24315286

**Comment by wifun** [comment]
Thanks for disabling the link!

What about the selectConnectionTab, for example in the case where the user already has that panel open when the designer changes to readonly

**Comment by hartra344** [comment]
Setting the designer to readOnly is not something we intend to support fully. Why would we? Maybe they want to make another change whilet he save is happening because they forgot something? Why should that not be allowed?

For the second case, I still don't see that as a reason to switch to readOnly, readOnly for hte entire designer is a very very heavy handed thing to do. It's really designed for a case of either monitoring view or user has read permissions but not write permissions.

**Comment by hartra344** [comment]
I'm ok with Power Automate making changes, but I do think changes at that level should be discussed before a PR is created to avoid wasting time. 

I actually think for copilot the overlay would be a better experience to tell the customer the readOnly context has switched. Switching it to just readOnly can actually be quite confusing

**Comment by wifun** [comment]
Sounds good, I suppose this behavior is sufficient for now
