### ISSUE TITLE
In new designer of logic app standard, pop-up to add CORS setting is showing up intermittently even after adding CORS setting

### ISSUE THREAD

**Issue by saroja-sattigeri** [Azure/LogicAppsUX#2819]
### Describe the Bug with repro steps

Customer is seeing pop-up(dialog notification to add CORS setting as part of hotfix to mitigate the issue discussed in below ICM and github issue) intermittently in their logic app standard while viewing run history even after adding CORS setting.

https://github.com/Azure/LogicAppsUX/issues/2499
https://portal.microsofticm.com/imp/v3/incidents/details/391863056/home

We collected HAR traces, see that customer received pop-up and CORS setting got added successfully however, it again showed up the notification:

Config:{Cors:{Dialog:{Update:{Button:{text:\"Add to CORS\"},Error:{message:\"**We were unable to add {portalUrl} to your CORS settings. You can do this manually by going to the CORS menu item in the Logic Apps.\",title:\"Unable to update CORS\"},InProgress:{message:\"Adding the url {portalUrl} to your CORS rules**\",title:\"**Updating CORS Rules**\"},No:{Permission:{message:\"I**n order to see inputs and outputs you will need to add {portalUrl} to the allowed origins list in the API CORS settings.\"}},Success:{message:\"Successfully added the url {portalUrl} to your CORS rules\",title:\"Successfully updated CORS rules\"}**,message:\"**In order to see inputs and outputs you will need to add {portalUrl} to the allowed origins list in the API CORS settings. We can add this for you, but you may continue seeing the error for a few seconds while the backend updates.\",title:\"Inputs and outputs are not loading due to the CORS policy**\"}}}}

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using Preview Designer or GA Designer

Generally Available

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome
Edge

AB#24345225

**Comment by ccastrotrejo** [comment]
Hi @saroja-sattigeri, could you please share with me the HAR network traces when this happens? You can send those to ccastrotrejo@microsoft.com

**Comment by alavudeen001** [comment]
Probably i can add my observations.

When Logic app standard has Access Control enabled (Logic app standard -> Settings -> Networking -> Inbound (Access control) this error pops up. The error message is misleading here. please see below screenshot.

The solution to the issue is : Adding Client IP in the Access Control. (https://learn.microsoft.com/en-us/answers/questions/1302541/unable-to-access-input-and-outpu-data-for-triggers)

**Ask**: can we please update pop up with right error message ?

![image](https://github.com/Azure/LogicAppsUX/assets/131970898/0e943593-b677-469f-8c97-d963c54328f6)

**Comment by Eric-B-Wu** [comment]
@alavudeen001 thanks for providing context on this. The current issue is that we can only tell when inputs/outputs are not being populated - when this occurs, we show this popup - CORS being the most common reason of why inputs/outputs not being shown. 
When another reason, such as when inbound network access is being prevented, inputs/outputs are once again not being populated, but this time it's not because of CORS. The issue is that there can be a number of reasons why this is happening, and the correct fix for it may not be possible to always be able to determined on our end, and thus cannot addressed in that error message. What we can do, however, is see whether or not CORS is set or not, and conditionally show this popup or a default popup to prevent any confusion for the user.
We have a issue to keep track of this here: https://github.com/Azure/LogicAppsUX/issues/2865
