### ISSUE TITLE
can not sign in into microsoft sentinel incident 

### ISSUE THREAD

**Issue by bhupender9878** [Azure/LogicAppsUX#2929]
### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {
      "Microsoft_Sentinel_incident": {
        "type": "ApiConnectionWebhook",
        "description": "",
        "inputs": {
          "host": {
            "connection": {
              "referenceName": null
            }
          },
          "body": {
            "callback_url": "@{listCallbackUrl()}"
          },
          "path": "/incident-creation"
        }
      }
    }
  },
  "connectionReferences": {},
  "parameters": {}
}
```

### Screenshots or Videos

<img width="1017" alt="Screenshot 2023-07-07 at 12 05 16 PM" src="https://github.com/Azure/LogicAppsUX/assets/126504776/d30b2a59-166a-4550-b12a-e3438492bf7b">

AB#24475676

**Comment by rllyy97** [comment]
Hi @bhypender9878, thank you for the bug report, however I am not able to reproduce your issue personally in both standard and consumption logic apps.
One thing we can try is having you create the connection in legacy designer, this will tell us if the issue is specific to new designer or something else.
You can find steps on how to access legacy designer here:
https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#fallback-to-legacy-designer
