### ISSUE TITLE
Code view UX is not good in new blade view

### ISSUE THREAD

**Issue by desertfoxmb** [Azure/LogicAppsUX#3101]
### Describe the Bug with repro steps 

1. Go to any Logic App 
2. Open designer view 
3. Click on Code view 

It is impossible to see all code (width) or even make sense of it in the blade because it cannot be resized to show more code, only scrolled horizontally which is not a good UX when the user has indicated they want to interact with the code view. Put it in a modal if you need to but if the user wants to see code view, let them see it, not part of it.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

AB#24774196

**Comment by e14mattc** [comment]
This issue is nearly a year old with no response :( The UI for the code view is frustrating. 

It also doesn't allow editing, which was something we could do in the legacy designer (which is now set for removal in September 2024). I've raised the editing issue here; https://github.com/Azure/LogicAppsUX/issues/5091

**Comment by hartra344** [comment]
This hasn't been prioritized because you can edit code from the code view in side panel. So far there has been a deliberate choice to not mix designer and code editing because it causes a lot of issues and can straight up breaking things causing a loss in data. The code view in designer is only read only to see the changes that will happen if you hit Save. The Menu Item is for editing.

**Comment by desertfoxmb** [comment]
There were also things that were very difficult if not impossible to do in the visual editor previously but were much easier in code view. Here's what I'm hearing:

Some business users might break things so no one gets a power user/developer experience.

This reduces the value prop for any savvy customer.

**Comment by e14mattc** [comment]
> This hasn't been prioritized because you can edit code from the code view in side panel. So far there has been a deliberate choice to not mix designer and code editing because it causes a lot of issues and can straight up breaking things causing a loss in data. The code view in designer is only read only to see the changes that will happen if you hit Save. The Menu Item is for editing.

Got it; I'd not spotted the Code View in the (left) side panel & was worried we were losing it entirely. I'm re-learning where to go to edit code & am fine with how it is in the new designer. Thanks for the response :)
