### ISSUE TITLE
impossible to update a pre-existent parameter

### ISSUE THREAD

**Issue by augustojaba** [Azure/LogicAppsUX#3151]
### Describe the Bug with repro steps

1. Go to a pre-existing logic app
2. Change to the new Logic App designer
3. Try to change a value of a Parameter

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

AB#24867131

**Comment by rllyy97** [comment]
Hi @augustojaba, I tried to reproduce your issue in both standard and consumption logic apps and both appear to be working as expected, I'm guessing the issue is specific to your logic apps / workflows.
If you could provide us with some more information about your apps, that would help us narrow down what the root cause is + find more accurate repro steps.
The main thing would probably be to supply your workflow.json (code view) file, if you're not comfortable sharing it publicly here you can send it to me directly at rileyevans@microsoft.com instead.
It might also help to send us your console error logs and a network logs of your workflow loading.
You can find steps for finding both in our documentation (link below) and again you can email me those files if you get them. 
https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors
