### ISSUE TITLE
Description missing in built-in operation group in Browse and Details view

### ISSUE THREAD

**Issue by speray** [Azure/LogicAppsUX#3248]
### Describe the Bug with repro steps

- Add an action
- Scroll to "Condition"
- Hover the "i" -> No description shown
- Click on Condition to go to the details -> No description show as well.

Note that the description is correctly shown when searching for "Condition" and hovering the "i"

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/12692545/6e91c7ac-3904-40ca-89a3-728f20a5d54b)
![image](https://github.com/Azure/LogicAppsUX/assets/12692545/9d03fdca-de17-47f5-949e-f58b7d0cce31)

### Browser

Any

AB#25059353

**Comment by Eric-B-Wu** [comment]
I don't seem to be able to reproduce this in Portal for logic apps, is this Power Automate specific?

**Comment by speray** [comment]
> I don't seem to be able to reproduce this in Portal for logic apps, is this Power Automate specific?

Yes most likely

**Comment by speray** [comment]
@Eric-B-Wu Please note that this is still a LogicAppsUX bug, since the display is inconsistent depending on if we're using a search or just scrolling the list (they should behave the same way).

**Comment by hartra344** [comment]
@speray, I'm not sure I understand how this is an LAUX bug? From what I can tell the behavior is exactly as expected in the Logic Apps Portal. That indicates there's an inconsistency in the Power Automate information being sent in and if I'm not mistaken y'all just broke apart from our search service features entirely for a more custom one.


https://github.com/Azure/LogicAppsUX/assets/13208452/c10d5c6b-4dbe-48f7-aa93-85036cfbb30d

I'm closing this unless you can show how it reproduced on the Azure Portal. Otherwise I'm assuming it's a host bug or backend bug on data retrieved for PA
