### ISSUE TITLE
Workflow expression window disappears

### ISSUE THREAD

**Issue by megamax34** [Azure/LogicAppsUX#3373]
### Describe the Bug with repro steps

- Go to a Logic app in the new view. 
- Click on an action and fill out a parameter value
- Use the expression window to write a workflow expression for that parameter value (dateDifference(............))
- Click on a different application window to reference something (Json payload in vs code that you are referencing etc)
- Click the expression editor window in the logic app to continue editing the expression.
- Expression editor window and the logic you wrote disappear.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

edge

AB#25243457

**Comment by preetriti1** [comment]
@megamax34 - Are you not able to click on the expression added earlier and see the expression window with the value?
<img width="884" alt="image" src="https://github.com/Azure/LogicAppsUX/assets/48265693/5e02e2d7-fae2-4a1a-babd-c44e75554b61">

**Comment by preetriti1** [comment]
This looks like a new feature, since we never persisted what the user is writing in the expression window unless they click on Add/Update button. this was to make sure we only save correct expressions, if we need to persist it then we need to think if we need to show the persisted value in editor even if it is opened in different parameter or action, or show some kind of warning to user that data will be erased before we auto close it.

**Comment by Eric-B-Wu** [comment]
A warning may be good; however, would we want to store the expression even when the user clicks on a separate parameter? This seems like it can cause some confusion especially if the user assumed the editor is closed when leaving the editor. Maybe something useful that can be done is instead keep a single global store of the expression editor state - and to add a button to update the editor to the last expression value

**Comment by Eric-B-Wu** [comment]
this from a developer standpoint would be easier as well, just cause each editor has its own token picker, so to keep track of each token picker state would be more difficult than just having a single global state

**Comment by megamax34** [comment]
So the issue was I had a json payload in a different application (Vs code)
that I was referencing while writing this expression. I had the expression
window open and half of the expression written but then I needed to
reference a separate Json payload in vscode. I clicked vscode and selected
the next file tab to reference the second json payload. In the portal I
could still see the expression window open but when I clicked to the
expression window to continue editing the expression it closed. No matter
where I clicked on the page or even if I just selected the browser itself
the expression window would close every time deleting the expression I had
in there. The expression window was auto closing anytime I left context of
the browser and went back. This does not happen in the OG logic app. The
expression window should only close if I click on the logic app canvas.

I am enjoying the new view though.

**Comment by Eric-B-Wu** [comment]
@megamax34 looking at this, it seems like it's happening due to the designer being an Iframe in azure portal, which is causing the designer to blur when switching application windows- closing the token picker/ expression editor. I think we can mitigate it for now by adding a paste option for your last expression - then create another github issue to see if we can propagate and not blur the editor

**Comment by Eric-B-Wu** [comment]
Will be fixed in this https://github.com/Azure/LogicAppsUX/pull/3636 change - expect it to be released in all regions 11/17
