### ISSUE TITLE
Every time I try to save within the preview designer it fails

### ISSUE THREAD

**Issue by pd-oflaherty** [Azure/LogicAppsUX#3509]
### Describe the Bug with repro steps

Create a logic app what a blob storage action for Get File and use the Access Key authentication method using the original designer. Now try switching to the preview designer, make some sort of edit (e.g. add a new action) and then save.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Edge

AB#25575746

**Comment by rllyy97** [comment]
Hi @pd-oflaherty are you still experiencing this error?  If so can you send me any console / network logs to my email at rileyevans@microsoft.com?  You can find steps to do so here: https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-console-errors

**Comment by pd-oflaherty** [comment]
Thanks for responding Riley.

I'm afraid that I have reverted to using the classic designer pretty much exclusively now. If I have an opportunity to try out the preview again and see the same issue I'll try to get the console/network logs.

Cheers
Paul
________________________________

**Comment by hartra344** [comment]
I'm not able to repro with the steps given so I'm assuming this has been fixed
![CleanShot 2023-12-06 at 20 33 47@2x](https://github.com/Azure/LogicAppsUX/assets/13208452/bf551eb0-2d25-49a9-9173-4caefe50a575)
@pd-oflaherty please let us know if this reoccurs and we can reopen the issue because it would likely be something deeper and we would need more information.
