### ISSUE TITLE
Token expiring constantly unable to save flow

### ISSUE THREAD

**Issue by ConnerBoastWork** [Azure/LogicAppsUX#3544]
### Describe the Bug with repro steps

Workflow validation failed for the workflow ''. {"error":{"code":"ExpiredAuthenticationToken","message":"The access token expiry UTC time '27/10/2023 13:00:08' is earlier than current UTC time '27/10/2023 13:03:02'."}}

Then I am unable to save the work.

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Browser

Chrome

AB#25617491

**Comment by rllyy97** [comment]
Hi @ConnerBoastWork, we have another work item we are using to track this issue here: https://github.com/Azure/LogicAppsUX/issues/3467
I'm going to close this item and you can follow updates on the other item.
Quick question though, when you say "expiring constantly" how long are you leaving the page open before the token expires?
Is it only after a few minutes and preventing you to save at all?  Or is it more after a few hours?

**Comment by ConnerBoastWork** [comment]
Its about 10-15 minutes I would say before it gives me that error.
