### ISSUE TITLE
Office 365 connection is not found in connections.json

### ISSUE THREAD

**Issue by mikaelsand** [Azure/LogicAppsUX#3952]
### Describe the Bug with repro steps 

1. Create a new Logic App project following [this official guide](<https://learn.microsoft.com/en-us/azure/logic-apps/create-single-tenant-workflows-visual-studio-code#add-the-office-365-outlook-action>) 
2. I add the Office 365 send and email (v2) action. 
3. I fill in the mandatory fields and save. 
4. I start debugging to test the Logic App locally. 
5. I get this error 

```text
Workflow Error: operationName='WorkflowDefinitionProvider.ProcessWorkflow', message='Workflow 'Stateful1' validate and create workflow operation failed, the exception is 'The API connection reference name 'office365' in action 'Send_an_email_(V2)' is invalid. No managed connection found by the API connection reference name 'office365' in connections.json file.
```

6. I check the connections.json file.

```json
{
  "managedApiConnections": {
    "office365": {
      "api": {
        "id": "/subscriptions/my subscription id/providers/Microsoft.Web/locations/eastus/managedApis/office365"
      },
      "connection": {
        "id": "/subscriptions/my subscription id/resourceGroups/MyResourceGroupName/providers/Microsoft.Web/connections/office365"
      },
      "connectionRuntimeUrl": "https://653b23c192477010.00.common.logic-eastus.azure-apihub.net/apim/office365/ae0e5432356441e5819da188842bb9d8/",
      "authentication": {
        "type": "Raw",
        "scheme": "Key",
        "parameter": "@appsetting('office365-connectionKey')"
      }
    }
  }
}
```

7. IMO the connection is there with the correct name.
8. I check that the connection has been created in Azure, which it has.

I have not updated any files using any other tools than the UI in VS Code.

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>)

Yes

### Workflow JSON

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "actions": {
            "Send_an_email_(V2)": {
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "referenceName": "office365"
                        }
                    },
                    "method": "post",
                    "body": {
                        "To": "mike@mail.com",
                        "Subject": "Hello from Logic Apps",
                        "Body": "<p><span style=\"white-space: pre-wrap;\">Hello from example workflow</span></p>",
                        "Importance": "Normal"
                    },
                    "path": "/v2/Mail"
                },
                "runAfter": {}
            }
        },
        "contentVersion": "1.0.0.0",
        "outputs": {},
        "triggers": {
            "When_a_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http"
            }
        }
    },
    "kind": "Stateful"
}
```

### Screenshots or Videos

*No response*

### Browser

Edge

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @mikaelsand is this issue still happening? It looks odd to me as I couldn't find that particular error log frontend area.

**Comment by ccastrotrejo** [comment]
Hey @sschutten, thanks for letting us know this. 
Which vscode extension version are you using? 

The only way I am able to repro this issue is when the `referenceName` property inside the `Send_an_email_(V2)` action in the `workflow.json` doesn't match the key in the `managedApiConnections` object in the `connections.json` file. 

It seems that Mikael's example does match, could you let me know if yours match?

**Comment by sschutten** [comment]
Hi @ccastrotrejo, sorry it took this long too respond. Yes, mine does also match.
- `referenceName` property inside the `Send_an_email_(V2)` action: `office365`
- key in the `managedApiConnections`: `office365`

**Comment by ccastrotrejo** [comment]
Hey @sschutten , this is a very odd behavior. The error explicitly states that the connection reference couldn't be found. Could you please zip your project folder and send it to me to my email? ccastrotrejo@microsoft.com

**Comment by sschutten** [comment]
I've send it to you. Looking forward if you can find anything in it :)

**Comment by ccastrotrejo** [comment]
Hey @sschutten thank you so much for sharing your project. I was able to repro the issue and I will fix it, I will also try to provide a workaround in the meantime

**Comment by sschutten** [comment]
That's great! Glad the project could be of any help! Looking forward to the fix/workaround.

**Comment by ccastrotrejo** [comment]
Hi @sschutten we just release a new version of the extension. This issue was specific to NuGet based projects. There are 2 workarounds/fixes for this.

1.- If you try to create a new project from scratch from new version this will be resolved. 


2.- Copy the following to the root host.json
`"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  }`
2.1.- Move/copy your connections.json to the root project folder
2.2.- Add the following to the .csproj file in the root folder:
` <ItemGroup>
    <None Update="connections.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>`


If this causes more trouble, please let me know. Thanks!

**Comment by bwornom** [comment]
Hi @ccastrotrejo, is it possible this issue is also affecting Get Entities(V2) for Azure Table Storage?  I am having the same issue with this extension

**Comment by ccastrotrejo** [comment]
Hi @bwornom its hard to tell if this is the same issue for this connector. Its been a while since we fixed this and I don't recall affecting other connectors. Could you please create a new issue overe here with the behavior you are experiencing? https://github.com/Azure/LogicAppsUX/issues This will help us triage it and see what is happening with your issue
