### ISSUE TITLE
LogicApps workflow timings are showing incorrectly 

### ISSUE THREAD

**Issue by MariamBrand** [Azure/LogicAppsUX#3975]
### Describe the Bug with repro steps 

These jobs that were run at 12:51 and 12:56pm timings are showing up as '0:51' and '0:56'

![LogicApps timig error](<https://github.com/Azure/LogicAppsUX/assets/156442611/b0897864-0c73-401b-8e8a-82c264aa69f1>)

This is across the board - wouldn't say this is to do with any workflow specifically.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Internet Explorer

### Additional context 

*No response*

**Comment by hartra344** [comment]
@mariambrand are you actually using internet explorer? If so that is a browser that is no longer supported by us or the Azure Portal. To show the times we use newer browser implemented localization APIs which IE would not have implemented.

For more information on which browsers are supported you can see here: https://learn.microsoft.com/en-us/azure/azure-portal/azure-portal-supported-browsers-devices

**Comment by MariamBrand** [comment]
Apologies, just realised have been using Microsoft Edge

**Comment by hartra344** [comment]
Can you provide information for the second question? I’m not able to repro this using english-US

**Comment by hartra344** [comment]
you can get it from the Azure Portal like this

https://github.com/Azure/LogicAppsUX/assets/13208452/9176c546-9203-43dd-8f3d-73ab717d57f5

ere

**Comment by hartra344** [comment]
Looks like this is a known bug in the Chrome browser(and by extension edge since it uses chromium under the hood). I'll check if there's some way to hack around it or if it's set to be fixed by them.
