### ISSUE TITLE
Not able to send notification to teams channel

### ISSUE THREAD

**Issue by avaya-schhajed** [Azure/LogicAppsUX#4313]
### Describe the Bug with repro steps 

I am trying to send alert I get through http request to Teams channel. But, it's not working in any case. We have a prod release next week. 

 Please keep it on priority

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Can you please provide some more information or repro steps on what is happening? I'm actually going to close this because there really isn't anything to go off of here. If it's an urgent production level issue I highly recommend opening an Azure Support case so our support team can help get the information we need to help.
