### ISSUE TITLE
new designer is not handling the parameter type undefined scenario properly

### ISSUE THREAD

**Issue by Xiaoyu-Huang** [Azure/LogicAppsUX#4323]
### Describe the Bug with repro steps 

The new designer is not handling the parameter type undefined scenario properly. Maybe it is by design I am not sure.

 I checked the logic app portal UX code. it is merging the definition.parameters with property.parameters. As "type" is only defined in definition.parameters.

By looking at how designer handles the parameters, I am wondering it might be a bug there.

[LogicAppsUX/libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts at 1f700e0824a59032d420420239913b423ec18a8e · Azure/LogicAppsUX (github.com)](<https://github.com/Azure/LogicAppsUX/blob/1f700e0824a59032d420420239913b423ec18a8e/libs/designer/src/lib/core/actions/bjsworkflow/serializer.ts#L208>)

![image](<https://github.com/Azure/LogicAppsUX/assets/22843713/51b3d692-ad0d-4024-92d0-6f6ae6b30518>)

I think the right logic should be

 typeof value == 'string'

 ? value

 : JSON.parse(value);

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Edge

### Additional context 

*No response*

**Comment by rllyy97** [comment]
As far as the `typeof value == 'string'` goes I think how we have it is correct, the JSON.parse method takes a string input, so if it's not a string we return it, and if it is a string we parse it to convert it back to an object

**Comment by rllyy97** [comment]
Hi @Xiaoyu-Huang, I'm a little confused on what your issue behavior is, can you expand more on "The new designer is not handling the parameter type undefined scenario properly."?  Workflow parameters should always have both a type and a value so if you're seeing some sort of error state it might be expected.

**Comment by Xiaoyu-Huang** [comment]
The new designer is merging the parameter in definition and also parameter. Only the parameter in definition is defining the parameter type.  


`{
definition: {
properties: {...}
},
properties:{}
}`

Let's forget about the logic to merge the parameters from workflow json. Just by looking at the code below, I feel the right logic should be below. Basically, if the type of the value is string, directly take the value otherwise, parse as JSON type.

`    parameterDefinition.value = equals(parameterDefinition.type, UIConstants.WORKFLOW_PARAMETER_TYPE.STRING)
      ? value
      : value === ''
      ? undefined
      : typeof value === 'string'
      ? value
      : JSON.parse(value);`
![image](https://github.com/Azure/LogicAppsUX/assets/22843713/d1cf3cab-47c4-4712-bfeb-b6e19a889300)

**Comment by rllyy97** [comment]
@Xiaoyu-Huang Again I'm confused on what your actual issue behavior is, in portal / vscode / otherwise.  Can you expand more on "The new designer is not handling the parameter type undefined scenario properly." as far as what a user might see when they experience this bug?  I'd like to be able to reproduce the bug but I'm not sure what you're actually trying to point out as a bug.  Like I said previously, workflow parameters should always have both a type and a value so if you're seeing some sort of error state it might be expected.

And to note on the JSON.parse function, JSON.parse takes a string input and converts it to a js object, so our implementation as we have it seems to be correct.  If it's not a string, return it, if it is a string, convert it to a js object.
