### ISSUE TITLE
Parse JSON  Schema option not at all loading in data operation of logic app

### ISSUE THREAD

**Issue by kapuchandra** [Azure/LogicAppsUX#4623]
### Describe the Bug with repro steps 

1\.create logic app and deploy 

 2\.select recurssion and time stamp selected to trigger logic app

 3\.select sql to execute store procedure

 4\.selected parse json to check the out put of return store procedure

 5\.parse json schema always showing loading .

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Screenshot 2024-04-16 at 1 03 34 PM](<https://github.com/Azure/LogicAppsUX/assets/159407487/f5518303-39c1-4755-8583-aa8591434e72>)

### Browser 

chrome

### Additional context 

trying to parse json of store procedure data but not able to schema to select in parse json of data operation in logic app

**Comment by Eric-B-Wu** [comment]
@kapuchandra this is happening because somewhere your network is blocking our CDN request for Monaco. We've recently moved the logic to load monaco in the [build](https://github.com/Azure/LogicAppsUX/pull/4401)  rather than through a network request that can be blocked (which can be blocked if you are located in China/ Egypt or if you have strict firewall policies). We expect the release to be going out this week.
