### ISSUE TITLE
Logic App Standard Designer won't open in VS Code/Chrome

### ISSUE THREAD

**Issue by TheAnonymousJackal** [Azure/LogicAppsUX#4624]
### Describe the Bug with repro steps 

1. Right click on your workflow. 
2. Select "Open designer" 
3. The designer wont open with error message "Cant start the background design-time process" 

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/11866908/affaa062-fdac-4b04-b14f-684fa199b5d2>)

### Browser 

Chrome

### Additional context 

Plz send help.

**Comment by ccastrotrejo** [comment]
Hi @TheAnonymousJackal thanks for raising this issue, I have noticed this issue, but I haven't been able to repro it consistently. The main reason of it is because the `AzureWebJobsSecretStorageType` setting in the `workflow-designtime/local.setting.json` it getting updated to an empty string. Could you please update the property as below?

`"AzureWebJobsSecretStorageType": "Files"`


If this doesn't solve the issue please let me know

**Comment by TheAnonymousJackal** [comment]
Hi Carlos, sorry for the late answer.

Thank you so much for your assistance, this solved my problem.

Best regards,
Martin
***@***.***
Martin Fogelberg, Integration Consultant, Dekiru Solutions AB
mobile +46 730635021 | e-mail ***@***.******@***.***> | www.dekiru.se<http://www.dekiru.se/> | LinkedIn<https://www.linkedin.com/in/martin-fogelberg-b3a55a153/>

**Comment by ccastrotrejo** [comment]
Hey @TheAnonymousJackal , I am glad it worked for you. I was able to catch the scenario in which the local.settings.json but is still flicky. I will make the fix once I am 100% sure on it, thanks!
