### ISSUE TITLE
Too many logic map shapes/function are placed outside of the visible area, unable to change them after reopening save map in VS code

### ISSUE THREAD

**Issue by wiktorklusek** [Azure/LogicAppsUX#4652]
### Describe the Bug with repro steps

While working on mapping I have utilised a lots of functions shapes, which followed the required logic, but now after reopening saved map they  are being placed outside of visible area, hence making it impossible to edit the map. Can this be looked into?

### Screenshots or Videos

![image](https://github.com/Azure/LogicAppsUX/assets/63818570/41290a73-8fd9-403d-8715-1a840b73506d)

### Version

newest

### Additional context

As per screenshots, I am unable to move right as this is the limit, and shapes got placed over there authomatically. Can this area be extended, so I can place them elsewhere? Thanks

**Comment by DanielleCogs** [comment]
Hi @wiktorklusek I can look into this! Seems like the root of the issue is that your function positions are not loading properly, is that correct? So when you save the map and reopen it, the position of your function is lost? If so, the first fix might be to investigate that, instead of expanding the map area. Some follow up questions-
1. On first glance it seems like some of the functions are being loaded into the correct position, and some aren't, is that correct?
2. In the .vscode folder of your LA project, do you see a file named [your data map]DataMapMetadata.json? It holds the metadata of your map that is needed to load the functions correctly
3. Can you upload any error logs you see? Should be in "Output" tab and select 'Azure Logic Apps' from the dropdown

**Comment by wiktorklusek** [comment]
Hi,

1. Correct, after opening the map again, some functions are outside of the visible area, where I cannot move them back, to where I could work on them again. I cannot even remove them from there. 

2. I do not seem to be able to find the MetaData.json, can you point me in the right direction? Below is the folder structure:
![image](https://github.com/Azure/LogicAppsUX/assets/63818570/000417e4-d78e-4fca-854f-7fc4bd7f34bf)

3. No error logs, just shapes out of scope

**Comment by wiktorklusek** [comment]
Hi! 

Let me know if there is any fix for this planned in the near future, thanks :)

**Comment by DanielleCogs** [comment]
Thank you that is helpful! I haven't been able to reproduce the issue so far but will keep working at it. As a temporary solution, you could modify the metadata file, as it holds the XY coordinates of the function positions after you save. If you remove the file, it should reset the positions to the default. You can find the file in the .vscode folder in your screenshot.

**Comment by DanielleCogs** [comment]
@wiktorklusek are you still experiencing this issue? If so I can walk you through a workaround for the map. I am working on a more permanent fix, but we are focusing our development efforts on reworking some of these UI elements for a future release to prevent issues like this from happening in the future.

**Comment by wiktorklusek** [comment]
Hi!

Sure! What steps should I take for a workaround?

**Comment by DanielleCogs** [comment]
Could you upload your metadata file? I can help you to temporarily update the coordinates. If you do not see it, you can open up the mapper, and select 'Save' and the new metadata file should be saved to the same location!
