### ISSUE TITLE
When viewing a logic app workflow run, all actions show "Error loading inputs" in both the inputs and outputs

### ISSUE THREAD

**Issue by wilson-aw** [Azure/LogicAppsUX#4830]
### Describe the Bug with repro steps

1. Go to a Logic App workflow overview tab
2. Click on a run in the run history
3. Click on any action in the run history view
4. Both the inputs and outputs values show "Error loading inputs", for all logic apps / workflows / actions, regardless of the action type

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![ErrorLoadingInputs](https://github.com/Azure/LogicAppsUX/assets/169642588/79ac15d6-b0c1-47f7-a1ec-85a3d45bca73)

### Browser

Firefox

### Additional context

These are logic apps that have been designed in VS Code and deployed via Azure DevOps to the portal. These errors occur when viewing the logic app in the portal. If I run the same logic apps locally in VS Code, the inputs and outputs display correctly.

**Comment by wilson-aw** [comment]
Additional info - when I click on the Show raw inputs link, it always displays the following without any exception message details
![Error](https://github.com/Azure/LogicAppsUX/assets/169642588/f36bf3da-5bc8-4914-a5b6-7c6bd255e08f)

**Comment by ccastrotrejo** [comment]
Hi @wilson-aw thanks for raising this issue. I don't have in top of my head what might be the root issue. Is there any chance you can share with me the HAR file while you perform these two actions (Click on the failing action in the run history view and clicking in the Show raw input links)

Here is our guide on how to get the HAR file [collecting-network-logs-in-a-har-file](https://purple-pebble-0e11de71e.1.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file)
Please send the info to my email ccastrotrejo@microsoft.com, rather than posting it here.

**Comment by wilson-aw** [comment]
Hi Carlos,

Your request for networking data helped me track down the issue. It was blocking CORS requests from portal.azure.com. We have restricted public access to all our logic apps, and if I add https://portal.azure.com/ to the allowed cors origins, it still blocks but returns the blocked IP address. 

If I then add a rule to the networking to allow that IP address it now loads the inputs and outputs.

**Comment by wilson-aw** [comment]
As a suggestion, it would be helpful to display the error reason on the page so that it's much easier for others to track down the cause of any issues such as this. Just saying error loading inputs doesn't provide much guidance.
