### ISSUE TITLE
When pasting an action step, the Paste Action selection is missing

### ISSUE THREAD

**Issue by patrick-hofmann-carey** [Azure/LogicAppsUX#4851]
### Describe the Bug with repro steps

1. Edit a Logic App application
2. Copy an existing action
3. Attempt to paste an action as the next step 

### What type of Logic App Is this happening in?

Consumption (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Edge

**Comment by hartra344** [comment]
When asked for clipboard permissions from your browser did you hit accept? The designer uses the OS clipboard in order to do copy/paste of actions, this gives a lot of power to copy paste across workflows/browsers or even between vscode and portal. But if you blocked that, you’ll never see the paste action until you go into your permissions and approve it.

**Comment by patrick-hofmann-carey** [comment]
Browser preventing it.. Resolved now
