### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by mattyjbennett** [Azure/LogicAppsUX#4857]
### Describe the Bug with repro steps

1. In VS Code, In Explorer view right-click on a workflow.json file. 
2. Select 'Open Designer'
3. The workflow tab appears but nothing renders. I get an error message: "Error: Cannot read properties of undefined (reading 'type')"

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Workflow JSON

```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "actions": {},
    "contentVersion": "1.0.0.0",
    "outputs": {},
    "triggers": {}
  },
  "kind": "Stateful"
}
```

### Browser

Not applicable

**Comment by mattyjbennett** [comment]
Hi Carlos,

We've had this problem twice now. The first time was due to an empty workflow.json file I forgot about. Removing it fixed the problem.

However this time that is not the case. Other Github/Terraform repos open fine, but just not this one. I am suspecting an issue in the logic app rather than in any of the workflows, this time. 

No other actions were performed. I opened my Repo folder in VSC, right clicked on the workflow.json file in the file explorer and selected 'Open Designer'. 

The extension version is v4.13.2

![Capture](https://github.com/Azure/LogicAppsUX/assets/156820476/9eeb9d18-f66c-40c0-a16c-f4eec838bb89)

**Comment by ccastrotrejo** [comment]
Hi @mattyjbennett all right, this makes more sense now. Unfortunately, I am not 100% sure what the issue is, I know that the issue is coming from the extension bundle which is the backend we use for the extension. I will start an internal email thread to improve this kind of experience when something goes wrong from that side. 
In the meantime, please try the following workaround:

- Close all vscode instances
- Go to the following folder in your computer `Users/<username>/.azure-functions-core-tools/Functions/ExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle.Workflows`
- Delete all the folders inside the above folder
- Open vscode again with your Logic App project
- Try to open Designer (it will take longer since it will start the design-time API and download the extension bundle)

Please if the issue keeps happening, let me know

**Comment by mattyjbennett** [comment]
Hi Carlos,

I've done a func host start --verbose. Most if it loads ok but there was an error:

[2024-05-23T13:37:51.306Z] There was an error performing a read operation on the Blob Storage Secret Repository.
[2024-05-23T13:37:51.307Z] Azure.Core: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Http: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Sockets: No connection could be made because the target machine actively refused it.
[2024-05-23T13:37:51.331Z] A host error has occurred during startup operation 'b48f4fcb-a82a-4d9f-a498-599fd0f9f4ad'.
[2024-05-23T13:37:51.331Z] Azure.Core: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Http: No connection could be made because the target machine actively refused it. (127.0.0.1:10000). System.Net.Sockets: No connection could be made because the target machine actively refused it.

The issue is only in this one repo.

**Comment by ccastrotrejo** [comment]
Hey Matthew, 
Could you please check if the following properties exist in the `workflow-designtime/local.settings.json`? If not could you please add them under the `Values` property in the JSON? Thanks

"AzureWebJobsSecretStorageType": "Files",
"FUNCTIONS_WORKER_RUNTIME": "node"
