### ISSUE TITLE
Error during deployment script generation: Error in setupWizardScriptContext

### ISSUE THREAD

**Issue by MarkJoyce0111** [Azure/LogicAppsUX#4924]
### Describe the Bug with repro steps

Create Logic App standard workflow
Generate scripts
then generate again

### What type of Logic App Is this happening in?

Standard (VSCode)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

No

### Browser

Chrome

**Comment by ccastrotrejo** [comment]
Hi @MarkJoyce0111 thanks for raising this issue, I was able to trace back the issue on our side but couldn't tell the actual root cause. This might be related to project structure or the path in which your project is

Is there any chance you can update the vscode extension and try again? 
If this doesn't work. Could you please share a copy of your project to ccastrotrejo@microsoft.com

**Comment by lambrianmsft** [comment]
@MarkJoyce0111 This is not a bug. This scenario occurs when the logic app is not selected before the "Generate deployment script" option is selected.

This is how the workspace should look when you generate the deployment script. Notice how the logic app "iacdemologicapp4" is highlighted.
![image](https://github.com/Azure/LogicAppsUX/assets/124318508/268df0e5-19f0-47d2-8b4b-cfa276a63632)

This below screenshot will result in the error that you encountered. Note how "iacdemologicapp4" is not highlighted.
![image](https://github.com/Azure/LogicAppsUX/assets/124318508/b6613182-2ce6-4fe6-afb8-c713384e7119)
