### ISSUE TITLE
Code view doesn't allow editing in new GA designer

### ISSUE THREAD

**Issue by e14mattc** [Azure/LogicAppsUX#5091]
### Describe the Bug with repro steps 

When using the new designer, select 'Code view', then try altering the code and it'll tell you it's read-only.

In the legacy designer, I could flip to the code view, then make & save edits to the JSON of the Logic App. This is especially useful when trying to repair API connections that have broken when you move a Logic App from one subscription to another.

Why is this edit capability missing from the new designer? Or am I overlooking a way to get to this?

There's a semi-related issue logged here re. the new code view being awkward to use in the docked area, which I full agree with; [https://github.com/Azure/LogicAppsUX/issues/3101](<https://github.com/Azure/LogicAppsUX/issues/3101>)

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![image](<https://github.com/Azure/LogicAppsUX/assets/9819307/216d67c7-2a8f-4560-8cfd-998abf1774b2>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by hartra344** [comment]
Which code view are you trying to edit in? If you're switching in the menu then it's supported. Editing in the flyout code view however isn't supported it's ready only.

**Comment by e14mattc** [comment]
I'm in this view here; i.e. the one I launch when I 'Edit' a Logic App... 
![image](https://github.com/Azure/LogicAppsUX/assets/9819307/dd3dfd5f-fe28-4800-98b9-8a09eec09956)

**Comment by e14mattc** [comment]
Ohhhh, I now see there's a 'Logic app code view' option in the left nav.. that is full screen & allows editing. Phew!
![image](https://github.com/Azure/LogicAppsUX/assets/9819307/abd81be0-ac59-4e0b-8b00-c9816ee868df)

**Comment by e14mattc** [comment]
Thank goodness that's there. I'm happy with it still existing somewhere.. it just needs me to re-think where I look for it & switch between the Design & Code views. 

Leaving these comments here to help anyone else wondering the same thing!

**Comment by LukasNespor** [comment]
Switching to completely different view does not make sense because it requires to save the Logic App in the first place. So how should I implement some change using the designer, then switch to the code in the same "session" to make some complex change, switch back to the designer and continue editing here without saving?

**Comment by FMHughes-work** [comment]
I agree with LukasNespor. I don't always flip back and forth between designer and Code View, but sometimes I need to. 
I usually enter the editor from the Overview because I want the full-width view on my monitor to see as much of the logic as possible. I've never noticed the new entry under Development Tools because that blade is hidden when you enter from the Overview.
