### ISSUE TITLE
Can't see to select the content returned from an inline js code action as input to a new function

### ISSUE THREAD

**Issue by brianodwyer** [Azure/LogicAppsUX#5120]
### Describe the Bug with repro steps 

I create a new action to call a SQL procedure and it has 1 parameter, 'JSON'. this is expected to be the body of a csv conversion script.

 In the new designer, I click on the Dynamic content icon and am shown file connector and variable content but not the Javascipt Code section. 

 If I save my work, switch to legacy designer and create the same action, I can now see the JavaScript Code section with my 'result' body in addition to the rest I could see before and can select it.

 I can create an expression to be body('my\_inline\_code') and it works but it is just invisible to the dynamic content picker.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

EGDE 126.0.2592.102

### Additional context 

*No response*

**Comment by rllyy97** [comment]
Hi @brianodwyer thanks for reporting your issue
It looks like the inline js operation output `result` is of type `object`, I'm able to see it in a following variable operation if I set the type to `object` as well.  For your SQL action input I'm guessing it is probably just a different type and that's why it's not appearing.  In the new designer, we decided to be more strict about enforcing types to match for inputs / output tokens.
For your situation you could try adding the token through the expression editor instead:

![image](https://github.com/user-attachments/assets/f3d92a97-9304-4d7e-8b41-5995b87c9196)

Let us know if you run into any more issues!

**Comment by brianodwyer** [comment]
Hi Riley,

Apologies if this reply re-opens the ticket. I wanted to thank you for the response, the explanation and the suggestion. I should have thought of that. Yes my SQL SP is expecting NVARCHAR(MAX). I am happy to change my code now.

Regards,
Brian.
