### ISSUE TITLE
Inconsistent behaviour in taking top 1 mail with filters from outlook

### ISSUE THREAD

**Issue by chandycab** [Azure/LogicAppsUX#5128]
### Describe the Bug with repro steps 

"fetchOnlyFlagged": false,

 "fetchOnlyWithAttachment": true,

 "folderPath": "Id::AQMkADcxN2NlYWZlLTM3NDctNDgzYy05MzY1LTEwNjQyMgAzNGE4YjIALgAAA5\_a-lvzWZJFh3J6svPHOwsBAP6YQvxndstMhd0a2NY2Un0AAAIBDAAAAA==",

 "from": "@{concat('email')}",

 "importance": "Any",

 "includeAttachments": true,

 "subjectFilter": "@{concat('Subject')}",

 "top": 1

Getting different top 1 mails in different times when we run the logic app

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json
"fetchOnlyFlagged": false,
                        "fetchOnlyWithAttachment": true,
                        "folderPath": "Id::AQMkADcxN2NlYWZlLTM3NDctNDgzYy05MzY1LTEwNjQyMgAzNGE4YjIALgAAA5_a-lvzWZJFh3J6svPHOwsBAP6YQvxndstMhd0a2NY2Un0AAAIBDAAAAA==",
                        "from": "@{concat('email')}",
                        "importance": "Any",
                        "includeAttachments": true,
                        "subjectFilter": "@{concat('Subject')}",
                        "top": 1
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by rllyy97** [comment]
Hi @chandycab thanks for reporting your issue, but it appears to be with the connector functionality rather than the logic apps designer.  For that kind of issue I'd recommend creating an Azure support request so that you can be directed to the proper assistance.  You can find information on that process here: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
