### ISSUE TITLE
Deleting workflow parameters not working

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5176]
### Describe the Bug with repro steps 

1. Create a workflow and author some workflow parameters in the panel. 
2. Try deleting some parameters and validate they are persisted as expected on closing the panel and opening again. 

**Expected:** Deleting some parameters and validate they should be persisted as expected on closing the panel and opening again.

**Actual:**Deleting some parameters and validate they are **not** persisted as expected on closing the panel and opening again. If we are changing the tab or discarding the changes made then we are able to see the deleted parameters after opening the panel.

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/cdbdd6e7-0f7a-4991-b413-a26ca64f4d1d](<https://github.com/user-attachments/assets/cdbdd6e7-0f7a-4991-b413-a26ca64f4d1d>)

![image](<https://github.com/user-attachments/assets/8587df42-7dca-44a9-b0ca-fba9fdea9790>)

### Browser 

Edge

### Additional context 

**Version:** 2\.40722.1.1

**Comment by rllyy97** [comment]
Hi @vgouth, I think this is expected behavior from what you've described.  The workflow parameters are only saved once you save the workflow itself.  If you navigate away and come back without saving, those parameters should reappear.  Also if you click the `Discard` command bar button, that will revert any deleted workflow parameters and bring them back.
If I'm misunderstanding your issue please feel free to add more context and we can investigate further.
Thanks!

**Comment by vgouth** [comment]
Hello @rllyy97, The workflow parameters are only saved once you save the workflow itself. If we navigate away and come back without saving, those parameters should reappear, **but it is not happening in this case**. That is the bug I have logged for. Please check the video attached for reference. If still the issue is not so clear, we can connect offline for furthermore clarification.
Thanks!
