### ISSUE TITLE
[for each] action been added automatically when using the dynamics contents

### ISSUE THREAD

**Issue by ZhouYiyun001** [Azure/LogicAppsUX#5191]
### Describe the Bug with repro steps 

■summary of this problem 

 Cx is facing an issue when using Standard Logic Apps that the [for each] action will been added automatically when using the dynamics contents in the next action.

 We reproduced this issue in the stateless workflow in Standard Logic Apps using blob trigger and [Get blob content using path (V2)] action.

 and we find that the issue doesn't occur in stateful workflow,and consumption Logic Apps.

Action's name : Get blob content using path (V2)

[https://learn.microsoft.com/en-us/connectors/azureblob/#get-blob-content-using-path-(v2](<https://learn.microsoft.com/en-us/connectors/azureblob/#get-blob-content-using-path-%28v2>))

■How to reproduce this problem

 st1.Create a stateless workflow in Standard Logic Apps

st2.Add [When a blob is added or modified (properties only) (V2)] as a Trigger

st3.Add [Get blob content using path (V2)] as an action

st4.Select dynamics contents [List of File Path] as the parameter in [Get blob content using path (V2)]action, Found that [For each] action has been added automatically.

 this issue not only occurs in blob action but also occurs in other actions when import dynamics contents in the parameter

### What type of Logic App Is this happening in? 

Standard (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

edge

### Additional context 

*No response*

**Comment by ZhouYiyun001** [comment]
■How to reproduce this problem
st1.Create a stateless workflow in Standard Logic Apps

st2.Add [When a blob is added or modified (properties only) (V2)] as a Trigger
![IMG_1516](https://github.com/user-attachments/assets/2cfd8580-834c-4cb3-9293-86da382aec2a)

st3.Add [Get blob content using path (V2)] as an action
![IMG_1518](https://github.com/user-attachments/assets/6585e08e-733c-4834-92e0-2003639650fb)

st4.Select dynamics contents [List of File Path] as the parameter in [Get blob content using path (V2)]action, Found that [For each] action has been added automatically.
this issue not only occurs in blob action but also occurs in other actions when import dynamics contents in the parameter

![IMG_1519](https://github.com/user-attachments/assets/0a07ae90-05f3-4ff0-9ad2-e204bbcfabd4)

![IMG_1520](https://github.com/user-attachments/assets/35de4a44-d9b2-4820-93ba-f3da807a4cfc)
![IMG_1521](https://github.com/user-attachments/assets/6c6ed5b3-7734-4402-b5c4-47e90cab5a15)

**Comment by ccastrotrejo** [comment]
Hi @ZhouYiyun001 thanks for raising this issue. As far as I know this is the expected behavior. As the dynamic conent that you want to set as input is "The path of the file or folder", this means that is individually by file or folder, meaning that once the action get the list of files/folders it needs to iterate throught every file/folder to get the path of it. Thats the reason it adds automaticallyt the foreach action. 

What its odd is that it is not doing it for stateful and consumption. I will check on those

**Comment by JMTK** [comment]
Yeah... it keeps nesting the for each every time I add any dynamic content field to my message
![image](https://github.com/user-attachments/assets/fa617445-9989-4389-ab82-6108eb3f4cce)

**Comment by hdilantha** [comment]
Having the same issue here. Worst part is that the automatically created For each actions comes with invalid parameters.

**Comment by Eric-B-Wu** [comment]
> Hi @ZhouYiyun001 thanks for raising this issue. As far as I know this is the expected behavior. As the dynamic conent that you want to set as input is "The path of the file or folder", this means that is individually by file or folder, meaning that once the action get the list of files/folders it needs to iterate throught every file/folder to get the path of it. Thats the reason it adds automaticallyt the foreach action.
> 
> What its odd is that it is not doing it for stateful and consumption. I will check on those

we should verify if this was a recent regression, think there were some implicit for each changes here: https://github.com/Azure/LogicAppsUX/pull/5149/files

**Comment by ccastrotrejo** [comment]
Hi @hdilantha, @JMTK  is this just happening on you on stateless logic apps?

**Comment by ccastrotrejo** [comment]
Ok, I found the root cause of why this is happening. 
This is happening by design; stateless workflows don't support `Split on` in triggers. The `Split on` option is based on the `triggerBody()` and the number of elements it has. For example, if the triggerBody is an array of five paths, the stateful workflow will run 5 times. For this case, runs the workflow based on the `"@triggerBody()?['Path']"`. This allows the workflow to not put the action inside a foreach loop (naturally, the workflow will handle the different paths) and run multiple times. 

If you disable the `Split on` option in the trigger for stateful workflows, the behavior will be nesting the action in a foreach
<img width="657" alt="image" src="https://github.com/user-attachments/assets/e99ac770-56e2-4ea9-a86d-df1cb168124d">

As stated before, as the dynamic content that you want to set as input is "The path of the file or folder", this means that is individually by file or folder, meaning that once the action get the list of files/folders it needs to iterate through every file/folder to get the path of it. Thats the reason it adds automatically the foreach action.


You can read more about this here https://michalmolka.medium.com/azure-logic-app-split-on-and-for-each-1f25dc554145

**Comment by hdilantha** [comment]
I think I may be experiencing a specific case. 

I am trying to "create a blob" for each attachment "when a new email arrives". 

After I added the trigger, I added the action to create a blob. When I give the attachment name as the blob name to be created, it adds two nested for loops.

![image](https://github.com/user-attachments/assets/048b2257-252e-4789-be11-340e36e98a4e)

One for loop is expected behavior since it should loop through all the attachments of the email. 

![image](https://github.com/user-attachments/assets/8cf80015-4297-434c-9c08-c27bcd88d91c)

But it adds a second for loop that tries to loop a "value" (image 3) which is not available in the trigger. This occurs an errors when the trigger is run.

![image](https://github.com/user-attachments/assets/82819dbf-38ae-4978-a9a8-cba96cdeac2a)
