### ISSUE TITLE
Testing Icon for individual actions does not disappear after disabling the "enable static result"

### ISSUE THREAD

**Issue by cam96** [Azure/LogicAppsUX#5217]
### Describe the Bug with repro steps 

The icon at the bottom-right of an action to indicate that the action is using mock data is always present even after disabling the mock data.

1. Create an empty workflow with an http trigger 
2. Add an HTTP action 
3. Click into the action 
4. Click "testing" 
5. Click "enable static result" 
6. Choose success and enter a json body as the output 
7. Click save 
8. Run the workflow 
9. Open designer 
10. It will display a little testing icon in the bottom right of the action 
11. Click into the http action 
12. Click "testing" 
13. Turn off "enable static result" 
14. Click save 
15. The little testing icon at the bottom right of the http action still shows. 

### What type of Logic App Is this happening in? 

- Standard (Portal) 
- VSCode 

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![logic_app_bug](<https://github.com/user-attachments/assets/d65cfee5-45e9-4c09-847a-e7fa08328555>)

### Browser 

All browsers. I was using Chrome to reproduce.

### Additional context 

This is a bug that causes distress when moving workflows into production and testing environments. It gives the impression that an action is still using mock data when it is not.

**Comment by Eric-B-Wu** [comment]
Yep it is marked as a feature request, because this was the same design as old designer; where static results is stored separately from the parameter while still being linked. Allowing users to reenable existing static results after disabling; however, given that we've had a couple of people marking this as an issue, I'll go ahead and implement a separate UI to remove the static result completely from action that way we still keep this existing feature

**Comment by Eric-B-Wu** [comment]
closing this which will come out in out 10/4 where users will be able to delete static results, removing testing icon
