### ISSUE TITLE
Input schema hierarchy visualization is not optimal

### ISSUE THREAD

**Issue by your-azure-coach** [Azure/LogicAppsUX#5306]
### Describe the Bug with repro steps 

It has been a design choice of the Data Mapper, to by default show only the input properties of the source schema that are being used. While it think this is a good decision, we loose track of the hierarchy with the current implementation. Please consider the screen recording below.

- The default behavior shows us two countryCodes. However, we do not know from where in the input hierarchy the country codes originate, unless we explicitly click on them.

 
- It would be great to change the default behavior and always show all parents nodes in the input schema, so we do not loose track of the input hierarchy. The end of the recording show the desired default behavior.

 

![DataMapper-InputSchema](<https://github.com/user-attachments/assets/ec4e766d-b61c-46ec-bdce-4220a73cfd27>)

### Screenshots or Videos 

*No response*

### Version 

v4.44.8 (however, not linked to this particular version, is general feedback)

### Additional context 

*No response*

**Comment by hartra344** [comment]
I'm going to close this issue, but it's not because we don't care or aren't fixing it, more as a sort of duplicate. We're currently in the process of overhauling the Data Mapper to address a lot of feedback like this and we expect it to be ready soon(it'll be in private preview in just a couple weeks). You can learn more here if you're interested: https://techcommunity.microsoft.com/t5/azure-integration-services-blog/upcoming-data-mapper-improvements/ba-p/4143271
