### ISSUE TITLE
Connection lines in Data Mapper are being visualized in a terrible way

### ISSUE THREAD

**Issue by your-azure-coach** [Azure/LogicAppsUX#5307]
### Describe the Bug with repro steps 

Please consider the mapping below. When connecting inputs to a function and functions outputs to other functions, the connection lines do not take the shortest "route" from input to target. This makes the mapping completely unreadable.

![DataMapper-MapLinks](<https://github.com/user-attachments/assets/0346e595-a314-4ec1-98ec-a95187871516>)

### Screenshots or Videos 

*No response*

### Version 

v4.31.7 (also applicable to other versions)

### Additional context 

*No response*

**Comment by your-azure-coach** [comment]
Extra info: I don't seem to have a metadata files as mentioned in this comment: https://github.com/Azure/LogicAppsUX/issues/4652#issuecomment-2070153353

**Comment by hartra344** [comment]
I'm going to close this issue, but it's not because we don't care or aren't fixing it, more as a sort of duplicate. We're currently in the process of overhauling the Data Mapper to address a lot of feedback like this and we expect it to be ready soon(it'll be in private preview in just a couple weeks). You can learn more here if you're interested: https://techcommunity.microsoft.com/t5/azure-integration-services-blog/upcoming-data-mapper-improvements/ba-p/4143271
