### ISSUE TITLE
[Templates][Single workflow] Create: Connections

### ISSUE THREAD

**Issue by bonicaayala** [Azure/LogicAppsUX#5314]
### Describe the Bug with repro steps

- Updates request: Templates - Single workflow
- Area: Create - Connections

### What type of Logic App Is this happening in?

Standard (Portal)

### Are you using new designer or old designer

New Designer

### Did you refer to the TSG before filing this issue? https://aka.ms/lauxtsg

Yes

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/c02e5ebf-d3b9-410d-87d7-2dc04cd29106)

### Browser

not applicable

**Comment by preetriti1** [comment]
@divyaswarnkar - Couple of questions for you -

-  I am assuming #1 is taken care by you because these text are updates in the template, @bonicaayala - please confirm if you meant clipping the sentence in just UI.
- for #3 what do we want to show for Get info link? For now I will update the text without Get info
- #5 will be a big change in every label we use in the designer not just this UI, please confirm this is how we want everywhere in the designer even in parameters and its connection creation. We are reusing connection create components and we want it to be consistent everywhere.
- for #6 again moving it to tooltips cause issues in aria description which is read out by navigator, to keep it consistent everywhere in our designer UI as well, is this change really needed?

@bonicaayala - for #7, there is an issue with styling and I am trying to work on it, I wont consider that as a release blocker but we do have bugs tracking that. I will change the text though for now.
