### ISSUE TITLE
V3 doesn't handle initializing arrays with different types the same way as V1

### ISSUE THREAD

**Issue by kisubedi** [Azure/LogicAppsUX#5337]
### Describe the Bug with repro steps 

[Bug 28553210](<https://msazure.visualstudio.com/One/_workitems/edit/28553210>): [V3] V3 doesn't handle initializing arrays with different types the same way as V1

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

*No response*

### Browser 

Chrome

### Additional context 

*No response*

**Comment by preetriti1** [comment]
@kisubedi - V1 is incorrectly serializing the variable, it is marked as Array type and still serializes as string, so that behavior is not correct. THe error you are seeing in V3 is because you have used single quotes and json parsing failed there... if you use double quotes it would work and it correctly serializes the array as [1, "2", true]..
anytime you have single quotes we can properly convert into JSON and hence it is treated as string and unfortunately the backend RP should have thrown validation error but it doesnt so it got saved. Ideally having type array and sending string should cause incorrect results in runtime, so giving this validation error is correct in client so user can convert into double quotes.

In other fields too we do the same thing for objects, any types
