### ISSUE TITLE
Is it possible to have multiple separate functions for a workflow workspace?

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [Azure/LogicAppsUX#5383]
### Describe the issue 

Is it possible to have 2 separate functions (in 2 separate files) in my Functions dir which can be found by the designer? I've tried to go through the wizard to add an azure function but I receive this error:

`spawn C:\WINDOWS\system32\cmd.exe ENOENT`

Are there any resources available for me to read about where the designer looks for these functions?

Here's my current dir structure:

![image](<https://github.com/user-attachments/assets/98c97a56-d430-4087-97a9-5db0ff832a88>)

I can see that when I `dotnet build` that my additional function generates metadata inside bin\Debug\net8\functions.metadata

Let me know if you need more info

### Are you using new designer or old designer 

New Designer (With action panels)

### Screenshots or Videos 

*No response*

### Browser 

na - using vscode

### Additional context 

*No response*

**Comment by wsilveiranz** [comment]
HI @Andrew-Lahikainen I had a chat with the custom code team and there is a bug today that makes the contract to not be updated. The fix for that is underway, but a workaround for that is do a dotnet clean before your dotnet build. According to the team, this will make the right contracts appear in the logic apps bin folder, which is what drives the designer to find them.  Let us know if that solves your problem for now.

**Comment by Andrew-Lahikainen** [comment]
This worked, thank you!
