### ISSUE TITLE
Unable to add a New step after two or more parallel branches.

### ISSUE THREAD

**Issue by PeterKlapwijk** [Azure/LogicAppsUX#5763]
### Describe the Bug with repro steps 

In the new designer I'm unable to add a new step after I have two or more parallel branches used.

 I need to switch back to the legacy designer to add a new step (to bring the branches together).

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![LA01](<https://github.com/user-attachments/assets/40398146-e82d-4a8b-bb93-b59e8bb93794>)

![LA02](<https://github.com/user-attachments/assets/767066ef-953c-4dff-82af-fb3650644588>)

### Browser 

Microsoft Edge

### Additional context 

*No response*

**Comment by hartra344** [comment]
This is by design. The right way to do this would be to add an action after a single path and then go to run after settings and add the other paths there. The reason for this is because while your example is balanced and simple, there were many many cases where this isn't the case and the + New Step button would be placed in an extremely confusing location that didn't properly show which paths would be combined. The new method takes a few extra steps but it's more explicit and more likely to be "correct".
