### ISSUE TITLE
Newline and Returns are double escaped

### ISSUE THREAD

**Issue by dripsjonlewis** [Azure/LogicAppsUX#5861]
### Describe the Bug with repro steps 

1. Click on the designer track to add a step 
2. In the action selector choose Compose 
3. In inputs click the function icon 
4. Type '\n\r' 
5. Look at codeview 
6. Expected: \n\r 
7. Actual double escaped n double escaped r 
8. This leads to parsing for data to not work let's say I wanted to set something up that was x lines down I would not be able to parse for or grab data from a resulting object or output 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

{

 "type": "Compose",

 "inputs": "\n\r",

 "runAfter": {

 "IsInPercentage": [

 "Succeeded"

 ]

 }

 }

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/c37f0af5-5bfa-4aef-853e-8b3fed533b8a>)

![Image](<https://github.com/user-attachments/assets/0bb79724-b00e-46d1-b7c1-92aead4f7177>)

### Browser 

Chrome

### Additional context 

Please don't get rid of the code view editor it's very useful for troubleshooting

**Comment by Eric-B-Wu** [comment]
Thanks for reporting this @dripsjonlewis, currently the editors will always escape control characters just due to javascript stringifying. And thus if you need the value to be "\n\r" I think the way to do it would to be through the code view editor (we won't be removing this). However, I do want to ask your usecase of "\n\r", as currently when using the `Enter` Key it'll give you the "\n" as the standard line break character

**Comment by Eric-B-Wu** [comment]
fyi I've fixed this issue: https://github.com/Azure/LogicAppsUX/pull/6131, but it'll be held due our deployment freeze until early - mid January
