### ISSUE TITLE
Monitoring view:  Not showing outputs data for some actions

### ISSUE THREAD

**Issue by vgouth** [Azure/LogicAppsUX#5908]
### Describe the Bug with repro steps 

1. Create a new Logic App Project 
2. Add a workflow to your local project 
3. Open the workflow.json file in designer and author a new workflow

 a. Add http request Trigger

 b. Add a compose action here with custom text

 c. Add a ServiceBus action. From the add new paramter dropdown add content and add random text in JSON format like {"a":"b"}

 d. Add a send email action with the body being the output of the compose action (step b)

 e. Add a new connection to your email action

 f. Add http response action 
4. Press F5 to build and run your project 
5. Run the workflow

 a. Open overview page. Right + Click on workflow.json file and "Overview"

 b. Copy call back URL from the overview page

 c. Send the http request POST via Postman and wait for the response 
6. Refresh the overview page and your should see your local run 
7. Open the monitoring view for your run from the overview page 
8. Verify the run details and action inputs and output 

**Expected:**Monitoring view should show all the inputs and outputs data.

**Actual:**Monitoring view not showing outputs data for some actions. When we click on show raw output we could see the data.

### What type of Logic App Is this happening in? 

Standard (VSCode)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/2b235e56-844a-47fb-ba18-c198f2386bd2>)

![Image](<https://github.com/user-attachments/assets/4d811371-f071-41b2-abc2-d4c39483bc4e>)

### Browser 

VS Code

### Additional context 

VSIX Version : 4.107.0

**Comment by rllyy97** [comment]
@vgouth Are you only seeing this in VSCode?  I just tried to repro in portal and I'm seeing the inputs an outputs as expected for the same actions

**Comment by rllyy97** [comment]
I'm seeing this issue in Portal as well, specifically on the Service Bus "Send message" action

**Comment by rllyy97** [comment]
It looks like in `libs\designer\src\lib\core\actions\bjsworkflow\monitoring.ts` we are relying on the output parameters from `rootState.operations.outputParameters`, and for the service bus send message action that data is empty.

**Comment by vgouth** [comment]
@rllyy97 Yes, issue repro only in VS code for response action. Agreed with service bus action has no outputs.

**Comment by rllyy97** [comment]
Related PR: https://github.com/Azure/LogicAppsUX/pull/5723

**Comment by ccastrotrejo** [comment]
I am removed the bug type in the issue. This is expected by design, as we agreed on the PR:

- Triggers and actions that don't have outputsLink will not show outputs sections.
- Foreach, Condition, Switch actions will follow the default binder and will show the outputs as it is now in production.
- Rest of the actions will rely on manifest or swagger based binding
- If there is an error while parsing, it will rely on the default parser which is the implementation in production.

The outputs that are seen are the outputs the status of the action itself, thera are no outputs that the user can use in the workflow
![Image](https://github.com/user-attachments/assets/14f88a31-a890-451f-b071-24d661a837fb)

If we see an increment of users complaining about this, I will bring this stuff to backend enginners to update the manifest of the actions
