### ISSUE TITLE
Columns parameters of action "Update item" of SharePoint connector, automatically disappear in Standard Logic Apps designer

### ISSUE THREAD

**Issue by ShingoHanai** [Azure/LogicAppsUX#5937]
### Describe the Bug with repro steps 

1. Create a workflow including action "Update item" to update selection column of SharePoint connector in Standard Logic Apps. 
2. Move to [Developer - Designer] blade to open designer from other blade, then within about 5 seconds edit other action's parameter and save workflow. 
3. Re-open designer in [Developer - Designer] blade, you can find parameter desappeared. 

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

[https://github.com/user-attachments/assets/16457416-4dd4-43c4-b3aa-6aa6ae5fd6b9](<https://github.com/user-attachments/assets/16457416-4dd4-43c4-b3aa-6aa6ae5fd6b9>)

### Browser 

Google Chrome

### Additional context 

*No response*

**Comment by rllyy97** [comment]
This looks like we are stripping away the values of dynamic parameters if we try to save before they load in.
If that is the case we may just need to prevent saving until all of the dynamic data is loaded.

**Comment by ShingoHanai** [comment]
It might be possiblity to cause unexpecteded workflow code change. If loading time needed to obtain completed workflow code, designer 
 UI should display message indicates warning like "Currently loading workflow code. Please wait edit any step".

**Comment by rllyy97** [comment]
Will be investigating this issue soon.

**Comment by bwelmers** [comment]
I submitted an issue with the same symptoms  (6015)

It feels like it happens most when I open a larger workflow, make a small edit, and save the workflow. It does not happen all the time but it has happened enough that my team now is concerned and second guessing our changes.

I did attach versions of the workflow (before and after the change) if you need to see how they look with the differences).

I think this issue has been happening for a month or more, but since most changes are not quick changes we don't see it happening too often.
