### ISSUE TITLE
Not able to open properties for failed component

### ISSUE THREAD

**Issue by dulibao** [Azure/LogicAppsUX#5942]
### Describe the Bug with repro steps 

Not able to open properties for failed component

![Image](<https://github.com/user-attachments/assets/fa92f2b2-8dd7-4f42-91ea-562d50d64aef>)

I've clicked on component to change setting and waited for 30 minutes. But it didn't open

 For some components it works but for some not

### What type of Logic App Is this happening in? 

Standard (Portal)

### Which operating system are you using? 

Windows

### Are you using new designer or old designer 

New Designer

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

*No response*

### Screenshots or Videos 

![Image](<https://github.com/user-attachments/assets/1589ef67-7da8-4f9d-9af9-236b6c69ab54>)

### Browser 

Chrome

### Additional context 

*No response*

**Comment by ccastrotrejo** [comment]
HI @dulibao thanks for raising this issue. There are a couple of reasons why this might be happening. 

In order to start figuring out why this is happening could you please let us know the following?

- Do you see any error/message in the console or network tab?
- Is there any chance we can get the HAR file when you load the run history tab? Here is a small guide on [Collecting network logs in a HAR file](https://agreeable-beach-04ed7ce1e.5.azurestaticapps.net/tsg#collecting-network-logs-in-a-har-file). You can send the file to my email: ccastrotrejo@microsoft.com

Thanks!
