### ISSUE TITLE
VS Code error popup - Cannot read properties of undefined (reading 'credentials2')

### ISSUE THREAD

**Issue by Rvgituser** [Azure/LogicAppsUX#6047]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: azureLogicAppsStandard.openDesigner

 Error type: TypeError

 Error Message: Cannot read properties of undefined (reading 'credentials2')

Version: 4.107.3

 OS: win32

 OS Release: 10.0.22631

 Product: Visual Studio Code

 Product Version: 1.95.1

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @Rvgituser, this issue gets fixed with this PR https://github.com/Azure/LogicAppsUX/pull/6014

The azure-account extension, which is the one we use to authenticate in vscode will be deprecated in Jan 2025, this PR changes the approach we use.

As for now the only workaround is to try to sign in using the following command from the command palette. Please make sure is the command azure-account.login
![Image](https://github.com/user-attachments/assets/90c49039-cc64-4078-9b94-615fa3dcdd21)
