### ISSUE TITLE
EnvrionmentCredential Error in VS code with logic apps only

### ISSUE THREAD

**Issue by juneesingh** [Azure/LogicAppsUX#6149]
Does this occur consistently?

Repro steps:

1. I installed VSCode, installed Functions, Azure Accounts, Logic Apps (Standard) extensions 
2. Downloaded code from here [https://github.com/Azure/logicapps/tree/master/ai-sample](<https://github.com/Azure/logicapps/tree/master/ai-sample>) 
3. Created project and trying to 'deploy logic app' using steps here: [https://github.com/Azure/logicapps/tree/master/ai-sample#follow-these-steps-to-create-the-azure-standard-logic-apps-project-and-deploy-it-to-azure](<https://github.com/Azure/logicapps/tree/master/ai-sample#follow-these-steps-to-create-the-azure-standard-logic-apps-project-and-deploy-it-to-azure>). Please note that I have successfully deployed a function app following the previous steps in the same article. Only logic apps dont work. 
4. Error: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit [https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot](<https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot>). 

The expectation is for the deployment to work. It is a fairly simple logic app with not many configurations.

I have reinstalled, restarted everything. Same behavior each time.

Action: azureLogicAppsStandard.createLogicAppAdvanced

Error type: Error

Error Message: Error in creating logic app. Error: Operation cancelled.

Version: 4.107.4

OS: win32

OS Release: 10.0.22631

Product: Visual Studio Code

Product Version: 1.95.3

Language: en

**Comment by ksks200** [comment]
Any update on this? We are facing the same error. We were previously able to deploy to logic app via VScode.

**Comment by ccastrotrejo** [comment]
Hi @ksks200 I have reached out to the owners of the package library that we use for the Authentication. As for now I haven't had a replied yet, but I just pinged them today for an update.

Do you see any errors in the console?

As a workaround you can downgrade the vscode extension version to 4.107.3.

**Comment by czm97176** [comment]
i am facing the same issue. Following is the error in the console

2:51:21 PM: Error: EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot.
[2024-12-03T14:59:31.971Z] The Azure Storage connection string is either empty or invalid. Unable to record diagnostic events, so the diagnostic logging service is being stopped.
[2024-12-03T14:59:31.971Z] Azure.Data.Tables: Value cannot be null. (Parameter 'connectionString').
[2024-12-03T14:59:31.977Z] Error occurred when attempting to purge previous diagnostic event versions.
[2024-12-03T14:59:31.977Z] Microsoft.Azure.WebJobs.Script.WebHost: Object reference not set to an instance of an object.

**Comment by Gokula2010** [comment]
@ccastrotrejo  Thank you for providing the private fix, I tested and now I can able to deploy the logic app without the above issue.

However, facing some unseen issues where the logic app workflow doesn't show the essential details like workflow status, workflow URL, and so on. Not sure whether the issue is with the logic app tool or an issue in the Azure portal that doesn't show the details.

However, I can't able to manually run the workflow which was developed and deployed from the Logic App tool from VSCode whereas I can able to see all the essential details of the workflow which was created from the Azure portal.

**Comment by Gokula2010** [comment]
Hi @ccastrotrejo, does the new release ([v5.13.0](https://github.com/Azure/LogicAppsUX/releases/tag/v5.13.0)) have your fix? 
Facing the same error "EnvrionmentCredential Error" after I updated to the new version

**Comment by ccastrotrejo** [comment]
Hi @Gokula2010 yes that v5.13.0 version should have the fix. 
About the issue in portal, while you were deploying the logic app by any chance did you also deployed your local settings?

**Comment by Gokula2010** [comment]
@ccastrotrejo I updated to v5.13.0 but still facing the same issue "EnvironmentCredential is unavailable. No underlying credential could be used. To troubleshoot, visit https://aka.ms/azsdk/js/identity/environmentcredential/troubleshoot."

However, I didn't face any issues when using your private fix v5.6.0. Could you please assist with this?

On the portal issue, I didn't explicitly deploy the local settings instead I updated all the settings manually before/after deploying the logic app.

**Comment by Gokula2010** [comment]
@ccastrotrejo Upon checking further, I can see that your PR still hasn't merged with the main, it is still in the open state.

https://github.com/Azure/LogicAppsUX/pull/6215

**Comment by ccastrotrejo** [comment]
Hi @Gokula2010 , you are right, sorry I got confused with the versions number and the v5.13.0 still doesn't have the change. I just merged the PR https://github.com/Azure/LogicAppsUX/pull/6215 and next version will have it. Please keep using the private vsix

**Comment by Gokula2010** [comment]
Hi @ccastrotrejo, Thank you.

Is there a suggestion on the portal issue - where the essential details ( like workflow status, workflow URL, and so on) don't appear when deployed from vscode, tried with the private vsix? thus, it doesn't allow me to trigger the workflow manually whereas, I can see all the essential details for the workflow which are directly created in the portal.

Additionally, I didn't see any such issue to see the essential details when tested earlier.

**Comment by ccastrotrejo** [comment]
Hi @Gokula2010 its kind of hard to tell what is the issue. Might be related to the runtime configuration of the logic app. By any chance did you also updated the `AzureWebJobsStorage` or the `APP_KIND` settings? If the essential details are not showing up its because the logic app is not configured correctly

**Comment by Gokula2010** [comment]
Hi @ccastrotrejo, I verified that AzureWebJobStorage and APP_KIND settings are there and the runtime configuration was updated as expected. 

The issue is only for the workflows deployed from vscode, there was no issue when it was created via the portal. (I created workflow01 from vscdoe and deployed it to the logic app, after that, in the same logic app, I created workflow02 via the portal)
