### ISSUE TITLE
Initial variable set to Boolean by default

### ISSUE THREAD

**Issue by ikdv** [Azure/LogicAppsUX#6238]
### Describe the Bug with repro steps 

Add the "Initialize variable"

 Change the data type to Integer

 Do something else

 Go back to the variable and try to set the initial variable to 1, the only options are true or false.

I have to reload the page to take effect the change of data type

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

*No response*

**Comment by ccastrotrejo** [comment]
Hi @ikdv thanks for raising this issue. What do you mean with "Do something else" ? I tried to repro it but couldn't do it.

Could you please try it in the following private azure portal url and see if it still repros on your end? https://aka.ms/emastaging
This link has the latest changes on our end. This issue might have been fixed by now.

https://github.com/user-attachments/assets/1f4a513b-cb24-4a09-9997-419afba1672d
