### ISSUE TITLE
logicapp designer not startting from vscode

### ISSUE THREAD

**Issue by sumeranand-mns** [Azure/LogicAppsUX#6259]
Does this occur consistently? 

 Repro steps:

1\.

 2\.

Action: azureLogicAppsStandard.openDesigner

 Error type: ECONNREFUSED

 Error Message: connect ECONNREFUSED redacted:id

Version: 4.107.4

 OS: win32

 OS Release: 10.0.19045

 Product: Visual Studio Code

 Product Version: 1.95.3

 Language: en

<details><summary>Call Stack</summary>¨NBSP;<p></p><precode language="" precodenum="0"></precode><p></p></details>

**Comment by ccastrotrejo** [comment]
Hi @sumeranand-mns thanks for raising this issue.
Do you have storage emulator or azurite running and the connection string set to use dev storage. The connection string is set to that automatically when you create a workflow in VSCode but please check that your local storage emulator is running, that might be the problem here

Closed as duplicated for https://github.com/Azure/logicapps/issues/1188
