### ISSUE TITLE
Inconsistent code view number of lines, swapping between design and code view.

### ISSUE THREAD

**Issue by melindastewart** [Azure/LogicAppsUX#6265]
### Describe the Bug with repro steps 

1. Click on **Edit** in ribbon, opening New designer. 
2. Click on **Code view**. 
3. Scroll down and note the number of lines of code. 
4. Click on **Designer**. 
5. Click on **Code view**. 
6. Scroll down and note the number of lines of code. 

Sometimes it works fine, other times the number of code lines changes. 

 Also same experience when swapping between New and Classic designer.

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json
{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "Application_Outcome_Status_is_Updated": {
                "type": "ApiConnectionWebhook",
                "description": "Trigger Condition: Outcome Status = Offer Issued - Submitted to CS, QA Questions Answered = Yes, Campus Status != Application Success",
                "inputs": {
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['commondataservice']['connectionId']"
                        }
                    },
```

### Screenshots or Videos

*No response*

### Browser

Chrome

### Additional context

![Image](<https://github.com/user-attachments/assets/45deeb27-a394-4933-a0ca-9ec955a124b4>)

![Image](<https://github.com/user-attachments/assets/73c8556c-5539-4789-9160-91b57aa93256>)

**Comment by hartra344** [comment]
This is because both code views are not the same thing. When you click code view in the main menu, it's showing exactly what is saved on your Logic App, when you click on code view in designer, it's showing what the designer would compile to. It's not possible to show this differently because it's what allows you to edit the code for what's shown in designer without saving first. It's also what allows swapping back and forth between code view/designer view without saving first.
