### ISSUE TITLE
Xpath type guess

### ISSUE THREAD

**Issue by FlemmingJPetersen** [Azure/LogicAppsUX#6272]
### Describe the Bug with repro steps 

Create a variable SomeXML of the type string, give it some xml 

 Create a Initialize variable of the type integer call it Count.

 In the value write: xpath(xml(variables('SomeXML')),'floor(count(/Blocks/Block) div 5))')

When you run the logic app it fails in the Count variable with

BadRequest

 The variable 'Count' of type 'Integer' cannot be initialized or updated with value of type 'Float'. The variable 'Count' only supports values of types 'Integer'.

A workaround is to do some type converting:

 int(xpath(xml(variables('SomeXML')),'string(floor(count(/Blocks/Block) div 5)))'))

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

Yes

### Workflow JSON 

```json

```

### Screenshots or Videos

*No response*

### Browser

Firefox 133.0.3 (64-bit)

### Additional context

*No response*

**Comment by Eric-B-Wu** [comment]
The issue is with the xpath `div` operator which the functions library follows `if the types of both $operand1 and $operand2 are xs:integer, then the return type is xs:double.`. Given that logic apps currently only supports xpath1.0, we also cannot use the idiv operator, and thus for your function, it'll be recommended to wrap it with int() to enforce type conversion
