### ISSUE TITLE
Edit code view lines differ between environments.

### ISSUE THREAD

**Issue by melindastewart** [Azure/LogicAppsUX#6286]
### Describe the Bug with repro steps 

1. Open logicapp-submitapplication-uat 
2. Logic app code view under Development Tools (classic) will return code lines 1865 this is consistent with other environments 
3. Click on Edit>Code view in new designer from Overview ribbon, number of code lines shows as 1817. I understand this is just the designer rendering the code differently to the classic designer, however each time I do this, without changing code, the number of lines seems to be different, see another example where its showing number of lines as 1853. 

 Additionally, if I open the same code in a different environment, I get different number of lines in the newer code designer. 

### What type of Logic App Is this happening in? 

Consumption (Portal)

### Which operating system are you using? 

Windows

### Did you refer to the TSG before filing this issue? [https://aka.ms/lauxtsg](<https://aka.ms/lauxtsg>) 

No

### Workflow JSON 

```json

```

### Screenshots or Videos

![Image](<https://github.com/user-attachments/assets/81dd4982-9804-4135-9dfe-92f8eeb8cccb>)

![Image](<https://github.com/user-attachments/assets/57c28084-5852-460a-be72-0569222eb451>)

![Image](<https://github.com/user-attachments/assets/6bc7d3f1-07c8-4039-b8e2-6121eb1dd8d2>)

![Image](<https://github.com/user-attachments/assets/39d61089-ea33-4048-854e-748056c74781>)

![Image](<https://github.com/user-attachments/assets/35510889-d98c-4191-a986-426b1bf40b3a>)

### Browser

Chrome Version 131.0.6778.205 (Official Build) (64-bit)

### Additional context

Same process followed between 2 environments, and differing results in code lines. This makes it hard to know that when you've copied code from one environment to another and changed environment variables, that you have done this correctly.

**Comment by hartra344** [comment]
I've already addressed this in another issue that you opened. This is expected behavior for the time being, we're looking at moving the standalone code view to use the same process as designer code view just to remove confusion but that could cause issues as well.

It essentially boils down to though:
Stand alone code view is the code that is on the server completely untouched.
Codeview is designer is not a view of the code on server but a view of what code would be saved from the current designer state meaning it's going through a compilation process in the middle. This is not going to guaruntee it's the same code as on the server.
